services:
  app: 
    image: aljazkovac/nodeapp:latest
    ports:
      - "127.0.0.1:8080:8080"
    container_name: express-app

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 <em># Poll every 60 seconds</em>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: --label-enable